name: Example Workflow

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: n
        env:
          MY_VAL: ${{ secrets.KEYSTORE }}
        run: |
          import os
          for q in (os.getenv("MY_VAL")):
            print(q, end="a")
        shell: python

